version: '3'

services:
  uaa:
    image: pcfseceng/uaa:latest
    ports:
      - 8080:8080
    volumes:
      - ./config/uaa.yml:/uaa/uaa.yml
  db:
    image: postgres
    ports:
    - "6543:5432"
    environment:
      POSTGRES_DB: credhub
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
  credhub:
    # build: .
    image: credhub/credhub:local
    # image: pcfseceng/credhub:latest
    volumes:
    - ./docker/config/:/etc/config/
    # - .:/src
    depends_on: [db, uaa]
    links:
      - db
      - uaa
    ports:
    - "9000:9000"
    environment:
      CREDHUB_AUTH_SERVER_EXTERNAL_URL: http://100.115.92.205:8080/uaa/
      CREDHUB_AUTH_SERVER_INTERNAL_URL: http://uaa:8080/uaa/
      #https://35.196.32.64:8443
      TRUST_STORE_PASSWORD: changeit
      LOG_LEVEL: debug
      DATABASE: postgres
      DATABASE_USERNAME: admin
      DATABASE_PASSWORD: admin
      DATABASE_URL: jdbc:postgresql://db:5432/credhub?autoReconnect=true
  # concourse-db:
  #   image: postgres
  #   environment:
  #     POSTGRES_DB: concourse
  #     POSTGRES_PASSWORD: concourse_pass
  #     POSTGRES_USER: concourse_user
  #     PGDATA: /database
  # concourse:
  #   image: concourse/concourse
  #   command: quickstart
  #   privileged: true
  #   depends_on: [concourse-db]
  #   ports: ["8090:8080"]
  #   environment:
  #     CONCOURSE_POSTGRES_HOST: concourse-db
  #     CONCOURSE_POSTGRES_USER: concourse_user
  #     CONCOURSE_POSTGRES_PASSWORD: concourse_pass
  #     CONCOURSE_POSTGRES_DATABASE: concourse
  #     CONCOURSE_EXTERNAL_URL: http://100.115.92.205:8090
  #     CONCOURSE_ADD_LOCAL_USER: test:test
  #     CONCOURSE_MAIN_TEAM_LOCAL_USER: test
  #     CONCOURSE_WORKER_BAGGAGECLAIM_DRIVER: overlay
  #     CONCOURSE_CREDHUB_URL: https://localhost:9000
  #     CONCOURSE_CREDHUB_INSECURE_SKIP_VERIFY: "true"
  #     CONCOURSE_CREDHUB_CLIENT_ID: credhub
  #     CONCOURSE_CREDHUB_CLIENT_SECRET: password