spring:
   flyway:
     enabled: true
     locations:
       - classpath:/db/migration/common
       - classpath:/db/migration/${DATABASE}
   jpa:
     hibernate:
       ddl-auto: validate
   datasource:
     username: ${DATABASE_USERNAME}
     password: ${DATABASE_PASSWORD}
     url: ${DATABASE_URL}
   profiles:
     active: prod
